title = "configuration of rsync-os"

# [object storage's name] 
[minio]
  endpoint = "127.0.0.1:9000"
  keyAccess = "minioadmin"
  keySecret = "minioadmin"
  [minio.boltdb]
    path = "test.db"

[onedrive]
  path = "onedrive:repo"
  [onedrive.boltdb]
    path = "onedrive.db"
