title = "configuration of rsync-os"

# [object storage's name] 
[teambition]
  cookie = "TEAMBITION_SESSIONID=xxx; TEAMBITION_SESSIONID.sig=xxx"
  base = "mirrors/"
  [teambition.boltdb]
    path = "teambition.db"
